2014/12/07 22:09:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/programacion%203/hola/index.php/gii/model/index.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/gii/default/index.html
---
2014/12/07 22:09:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\programacion 3\yii\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/programacion%203/hola/index.php/gii/crud/index.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/gii/module/index.html
---
2014/12/07 22:51:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Clientes".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Clientes')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Clientes')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Clientes.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:51:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Clientes".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Clientes')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Clientes')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Clientes.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:51:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:51:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:52:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('Cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('Cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/Client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/Cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php
---
2014/12/07 22:52:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/clientes/Cliente.html
---
2014/12/07 22:52:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "cliente".' in C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(270): CController->missingAction('cliente')
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('cliente')
#2 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('clientes/client...')
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/programacion%203/hola/index.php/clientes/cliente.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/clientes/Cliente.html
---
2014/12/08 00:55:45 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php (73)
in C:\xampp\htdocs\programacion 3\hola\index.php (13)
2014/12/08 00:55:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\actions\CInlineAction.php(49): VentasController->actionCreate()
#4 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ventas/create')
#14 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/programacion%203/hola/index.php/ventas/create.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/ventas/create.html
---
2014/12/08 00:56:17 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php (73)
in C:\xampp\htdocs\programacion 3\hola\index.php (13)
2014/12/08 00:56:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\actions\CInlineAction.php(49): VentasController->actionCreate()
#4 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ventas/create')
#14 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/programacion%203/hola/index.php/ventas/create.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/ventas/create.html
---
2014/12/08 00:56:59 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php (73)
in C:\xampp\htdocs\programacion 3\hola\index.php (13)
2014/12/08 00:56:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`plasma`.`ventas`, CONSTRAINT `ventas_ibfk_1` FOREIGN KEY (`clientes_id_clientes`) REFERENCES `clientes` (`id_cliente`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `ventas` (`id_venta`, `fecha_venta`, `monto_fecha`, `clientes_id_clientes`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\programacion 3\yii\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\programacion 3\yii\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\programacion 3\hola\protected\controllers\VentasController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\actions\CInlineAction.php(49): VentasController->actionCreate()
#4 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\programacion 3\yii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ventas/create')
#14 C:\xampp\htdocs\programacion 3\yii\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\programacion 3\hola\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/programacion%203/hola/index.php/ventas/create.html
HTTP_REFERER=http://localhost/programacion%203/hola/index.php/ventas/create.html
---
